#!/usr/bin/env python3
from pathlib import Path
from datetime import datetime, timezone
import subprocess, json, hashlib, sys
R=Path.cwd(); REQ='8d274095b0e1acbe1fad0a73ef6a5293364902fc'; SB='cp20-e7r-b4-v2-stage0-finalization-handoff-20260904'; SRC='85f3daa617aaa245eb2b43c5b0cc425d669bb927'
SEAL='11456b7d6f673e5cab6079850731cbda70373b77e4e0f532089d6783fd16c78e'; MS='7f48807db5733c85759324d4f94e357aa6941de0ecd911b4180f5bc2101d6dcb'; CS='7f2531743db7c2987d6efa785784852bc6fe066ccc23cfc607296de96f3eb403'; CFGSH='2fbc7bd09ab2cae89095b537342cf63c85f53f821d4ddf21c7860a2ec53b1f4b'
BLOCK=['ec26b5fbbd89f0a8184486c82bbb34b6a810263a8b2016a17103cf8fda6ab41c','2e6d9e1d833fc8dabf02c0e970ccfb06fc86e4cbc9e85cd2e0e61ae3611879ea','66ac975940abb29a1248079ea6e03643ded966da296cf33deb7c7a0f5fa60eac','06768aebd233c874fbb2103f3f3ccadca7db5ae76c7f5fb051ab982cf737012f']
V='research_manager/results/CP20_TASK8B3_E7R_B4_TILTED_MICROCANONICAL_FOURIER_V2_STAGE0'; P='CP20_TASK8B3_E7R_B4_TILTED_MICROCANONICAL_FOURIER_V2'; CFG=f'{V}/{P}_CONFIG.json'; MAN=f'{V}/{P}_PRE_RUN_SHA256SUMS.txt'; CON=f'{V}/{P}_STAGE1_EXECUTION_INTEGRITY_AND_OUTPUT_CONTRACT.md'; AUTH=f'research_manager/decisions/{P}_STAGE1_AUTHORIZATION.json'; DEC=f'research_manager/decisions/{P}_STAGE0_ACCEPTANCE_AND_CANONICALIZATION_2026-09-05.json'; RA=f'research_manager/records/{P}_PHASE_A_READBACK_2026-09-05.json'; RB=f'research_manager/records/{P}_PHASE_B_READBACK_2026-09-05.json'; TX=f'research_manager/records/{P}_CANONICAL_TRANSACTION_2026-09-05.json'
CLAIMS={**{f'B4-N{i}':'NOT ESTABLISHED' for i in range(1,8)},'B4-CT':'NOT ESTABLISHED','E6-N2':'[OPEN]'}
def q(a,cap=False,text=True,ok=True):
 p=subprocess.run(a,cwd=R,capture_output=cap,text=text)
 if ok and p.returncode: raise SystemExit('FAIL '+' '.join(a)+(('\n'+str(p.stdout)+'\n'+str(p.stderr)) if cap else ''))
 return p
def o(a): return q(a,True).stdout.strip()
def hb(b): return hashlib.sha256(b).hexdigest()
def hf(p): return hb(Path(p).read_bytes())
def gb(c,p): return q(['git','show',f'{c}:{p}'],True,False).stdout
def ja(c,p): return json.loads(gb(c,p).decode())
def wj(p,x): Path(p).parent.mkdir(parents=True,exist_ok=True); Path(p).write_text(json.dumps(x,ensure_ascii=False,indent=2,sort_keys=True)+'\n',encoding='utf-8',newline='\n')
def cp(p):
 b=gb(SRC,p); Path(p).parent.mkdir(parents=True,exist_ok=True); Path(p).write_bytes(b); t=o(['git','ls-tree',SRC,'--',p]); mode,typ,blob,_=t.split(maxsplit=3); assert typ=='blob' and o(['git','hash-object',p])==blob; q(['git','update-index','--add','--cacheinfo',f'{mode},{blob},{p}']); return blob,hb(b)
def stage(st,x):
 st['active_task']['stage']=x
 if 'active_stage' in st: st['active_stage']=x
 if 'active_stage' in st.get('continuity',{}): st['continuity']['active_stage']=x
def verify(c,cfg):
 rr=[]
 for p,e in cfg['canonical_stage0_artifacts'].items():
  bl=o(['git','rev-parse',f'{c}:{p}']); sh=hb(gb(c,p)); good=(bl==e['git_blob_sha1'] and sh==e['sha256']); rr.append({'path':p,'expected_blob':e['git_blob_sha1'],'observed_blob':bl,'expected_sha256':e['sha256'],'observed_sha256':sh,'pass':good})
  if not good: raise SystemExit('[PHASE A CANONICALIZATION FAILURE] '+p)
 return rr
def up(rows,p,h):
 for r in rows:
  if r['path']==p: r['sha256']=h; return
 rows.append({'path':p,'sha256':h})
def an(p):
 rt='Collatz Problemi — Araştırma Arşivi'
 if p=='START_HERE_CURRENT_HANDOFF.md': return rt+'/CONTINUITY/'+p
 if p.startswith('research_manager/'): return rt+'/RESEARCH_MANAGEMENT/'+p[len('research_manager/'):]
 return None
def journal(rows):
 p=Path('research_manager/RESEARCH_JOURNAL.jsonl'); raw=p.read_bytes(); ls=raw.splitlines(); prev=hb(ls[-1]); seq=len(ls)+1
 if raw and not raw.endswith(b'\n'): raw+=b'\n'
 for r in rows:
  r={**r,'schema':'COLLATZ_RESEARCH_JOURNAL_V1','sequence':seq,'previous_entry_sha256':prev}; line=json.dumps(r,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode(); raw+=line+b'\n'; prev=hb(line); seq+=1
 p.write_bytes(raw)
def now(): return datetime.now(timezone.utc).isoformat()
q(['git','config','user.name','Canonical Integrator']); q(['git','config','user.email','actions@users.noreply.github.com']); q(['git','fetch','origin','+refs/heads/main:refs/remotes/origin/main',f'+refs/heads/{SB}:refs/remotes/origin/stage0']); assert o(['git','rev-parse','refs/remotes/origin/main'])==REQ and o(['git','rev-parse','refs/remotes/origin/stage0'])==SRC; q(['git','checkout','-B','main','refs/remotes/origin/main'])
st=json.loads(Path('CURRENT_RESEARCH_STATE.json').read_text()); assert st['active_integrator']['status']=='RELEASED' and not Path(AUTH).exists(); cfgb=gb(SRC,CFG); assert hb(cfgb)==CFGSH; cfg=json.loads(cfgb); assert cfg['authorization_model']['type']=='TWO_COMMIT_PHASE_A_PHASE_B' and cfg['future_authorization']['artifact_path']==AUTH; assert hb(gb(SRC,MAN))==MS and hb(gb(SRC,CON))==CS
for x in BLOCK: assert x in cfg['blocked_seal_blacklist']
for p,e in cfg['canonical_stage0_artifacts'].items():
 bl,sh=cp(p); assert bl==e['git_blob_sha1'] and sh==e['sha256']
extras=[CFG,MAN,f'{V}/{P}_PRE_RUN_SEAL.md',f'{V}/{P}_HANDOFF_VERIFICATION_EVIDENCE.json',f'{V}/{P}_HANDOFF_VERIFICATION_STDOUT.txt',f'{V}/{P}_FINALIZATION_MECHANICAL_CHECKS.json',f'{V}/{P}_STAGE0_FINAL_RECORD.json',f'{V}/{P}_SCIENTIFIC_PROGRAM_PRESERVATION.md',f'{V}/{P}_CANONICAL_INPUTS.md',f'{V}/{P}_AUTHORIZATION_BASE_SELF_REFERENCE_REPAIR_RECORD.json',f'{V}/{P}_CANONICAL_STATE_PATH_REPAIR_RECORD.json',f'{V}/{P}_BLOCKED_CANDIDATE_CLASSIFICATION.json']
for p in extras:
 if p not in cfg['canonical_stage0_artifacts']: cp(p)
wj(DEC,{'schema':P+'_STAGE0_ACCEPTANCE_V1','accepted_source_branch':SB,'accepted_source_head':SRC,'canonical_source_base':REQ,'seal_sha256':SEAL,'manifest_sha256':MS,'contract_sha256':CS,'config_sha256':CFGSH,'drive_folder_id':'1SFvk3A5fSzB4adPFIMxudgMdbooXVi3q','drive_file_id':'1hWN1mdJdx78jnsOlD2ZXF8htkf9e8QGL','drive_raw_readback':'PASS','scientific_diff':'NO SCIENTIFIC CHANGE','blocked_seals':BLOCK,'claims':CLAIMS,'stage1_executed':False,'T1_T8_executed':False,'seal_zip_materialized_on_main':False})
st['active_integrator']={'holder':'canonical-integrator-b4-v2-stage0-stage1-authorization-20260905','scope':'B4 V2 Stage0 canonical intake + two-commit Stage1 authorization only; no Stage1/T1-T8 execution, invalid V1 drafts, new mathematics, weighted/operator work or E8.','base_commit':REQ,'acquired_at':now(),'status':'HELD'}; SA='STAGE_0_REPAIR_ACCEPTED_AWAITING_AUTHORIZATION'; stage(st,SA); st['b4_v2_stage0']={'accepted':True,'accepted_source_branch':SB,'accepted_source_head':SRC,'canonical_source_base':REQ,'stage':SA,'seal_sha256':SEAL,'manifest_sha256':MS,'contract_sha256':CS,'config_sha256':CFGSH,'drive_folder_id':'1SFvk3A5fSzB4adPFIMxudgMdbooXVi3q','drive_seal_file_id':'1hWN1mdJdx78jnsOlD2ZXF8htkf9e8QGL','drive_raw_readback':'PASS','scientific_diff':'NO SCIENTIFIC CHANGE','blocked_seals':BLOCK,'claims':CLAIMS,'stage1_authorized':False,'stage1_executed':False,'T1_T8_executed':False,'authorization_count':0,'seal_zip_materialized_on_main':False}; st['b4_v2_reseal'].update({'stage':SA,'stage0_dispatched':True,'stage0_executed':True,'stage0_accepted':True}); st['documents'].update({'accepted_checkpoint_decision':DEC,'active_authorization_decision':None,'b4_stage1_execution_contract':CON,'b4_v2_stage0_config':CFG}); st['next_action']={'authorized_stage':'PHASE_B_ONLY_AFTER_PHASE_A_READBACK','executed_in_this_transaction':False,'instruction':'Create Phase B Stage-1 authorization only after exact Phase-A GitHub read-back PASS; do not execute Stage 1 or T1-T8.','prohibited':['Stage1 execution','T1-T8 execution','invalid V1 drafts','new mathematics','weighted/operator work','E8']}; wj('CURRENT_RESEARCH_STATE.json',st); q(['git','add','CURRENT_RESEARCH_STATE.json',DEC]); q(['git','commit','-m','Canonicalize accepted B4 V2 Stage0']); A=o(['git','rev-parse','HEAD']); assert o(['git','rev-parse','HEAD^'])==REQ; q(['git','push','origin','HEAD:main']); q(['git','fetch','origin','+refs/heads/main:refs/remotes/origin/main']); assert o(['git','rev-parse','refs/remotes/origin/main'])==A
ar=verify(A,cfg); assert q(['git','cat-file','-e',f'{A}:{AUTH}'],ok=False).returncode!=0; ast=ja(A,'CURRENT_RESEARCH_STATE.json'); assert ast['active_task']['stage']==SA and not ast['b4_v2_stage0']['stage1_executed'] and not ast['b4_v2_stage0']['T1_T8_executed']; RAO={'schema':P+'_PHASE_A_READBACK_V1','phase_a_commit_sha':A,'parent_sha':REQ,'canonical_artifacts':ar,'authorization_json_exists':False,'stage':SA,'stage1_executed':False,'T1_T8_executed':False,'verdict':'PASS'}; wj(RA,RAO)
auth={'authorized_v2_seal_sha256':SEAL,'v2_contract_sha256':CS,'canonical_stage0_base_sha':A,'stage':'STAGE_1_AUTHORIZED_NOT_EXECUTED'}; wj(AUTH,auth); st=json.loads(Path('CURRENT_RESEARCH_STATE.json').read_text()); SBST='STAGE_1_AUTHORIZED_NOT_EXECUTED'; stage(st,SBST); st['b4_v2_stage0'].update({'stage':SBST,'canonical_stage0_base_sha':A,'phase_a_readback':'PASS','stage1_authorized':True,'stage1_authorization_once_only':True,'authorization_count':1,'stage1_executed':False,'T1_T8_executed':False}); st['b4_v2_reseal']['stage']=SBST; st['documents'].update({'active_authorization_decision':AUTH,'b4_v2_stage0_phase_a_readback':RA}); st['next_action']={'authorized_stage':'STAGE_1_ONCE_ONLY','executed_in_this_transaction':False,'instruction':'Execute B4 V2 Stage 1 later once only in a fresh uncontaminated computation session; do not execute it in this integration.','prohibited':['Stage1 execution here','T1-T8 execution here','invalid V1 drafts','E8','new mathematics']}; wj('CURRENT_RESEARCH_STATE.json',st); q(['git','add','CURRENT_RESEARCH_STATE.json',AUTH,RA]); q(['git','commit','-m','Authorize B4 V2 Stage1 after PhaseA readback']); B=o(['git','rev-parse','HEAD']); assert B!=A and o(['git','rev-parse','HEAD^'])==A; q(['git','push','origin','HEAD:main']); q(['git','fetch','origin','+refs/heads/main:refs/remotes/origin/main']); assert o(['git','rev-parse','refs/remotes/origin/main'])==B; q(['git','merge-base','--is-ancestor',A,B]); arb=ja(B,AUTH); assert arb==auth and set(arb)==set(auth) and 'authorization_commit_sha' not in arb; bs=ja(B,'CURRENT_RESEARCH_STATE.json'); assert bs['active_task']['stage']==SBST and not bs['b4_v2_stage0']['stage1_executed'] and not bs['b4_v2_stage0']['T1_T8_executed']; br=verify(B,cfg); RBO={'schema':P+'_PHASE_B_READBACK_V1','phase_a_commit_sha':A,'phase_b_commit_sha':B,'phase_a_is_ancestor':True,'distinct_commits':True,'direct_child':True,'authorization_binding':arb,'authorization_self_reference_absent':True,'active_task_stage':SBST,'canonical_artifacts_unchanged':br,'stage1_executed':False,'T1_T8_executed':False,'verdict':'PASS'}; wj(RB,RBO)
tx={'schema':P+'_CANONICAL_TRANSACTION_V1','required_main':REQ,'accepted_source_branch':SB,'accepted_source_head':SRC,'phase_a_commit_sha':A,'phase_a_readback':'PASS','phase_b_commit_sha':B,'phase_b_readback':'PASS','authorized_seal_sha256':SEAL,'contract_sha256':CS,'manifest_sha256':MS,'config_sha256':CFGSH,'drive_stage0_folder_id':'1SFvk3A5fSzB4adPFIMxudgMdbooXVi3q','drive_stage0_seal_file_id':'1hWN1mdJdx78jnsOlD2ZXF8htkf9e8QGL','drive_stage0_raw_readback':'PASS','blocked_seals':BLOCK,'scientific_diff':'NO SCIENTIFIC CHANGE','claims':CLAIMS,'stage1_executed':False,'T1_T8_executed':False,'authorization_count':1,'authorization_once_only':True}; wj(TX,tx); st=json.loads(Path('CURRENT_RESEARCH_STATE.json').read_text()); st['b4_v2_stage0'].update({'authorization_commit_sha':B,'phase_b_readback':'PASS','stage1_authorization_status':'[AUTHORIZED ONCE — NOT EXECUTED]'}); st['continuity']['minimum_required_commit']=B; st['documents'].update({'b4_v2_stage0_phase_b_readback':RB,'b4_v2_canonical_transaction':TX}); st['active_integrator'].update({'released_at':now(),'status':'RELEASED'}); st['next_action']={'authorized_stage':'STAGE_1_ONCE_ONLY','executed_in_this_transaction':False,'instruction':f'Execute {P} Stage 1 exactly once in a fresh session that has not seen invalid V1 T1-T8 drafts, using canonical_stage0_base_sha={A}, authorization_commit_sha={B}, seal={SEAL}, contract={CS}.','prohibited':['blocked seals','invalid V1 drafts','canonical-integrator mathematics','unauthorized rerun','E8','weighted/operator work outside frozen fallback']}
h=f'''# CURRENT HANDOFF — B4 V2\n\nCanonical task: `{P}`\nActive stage: `STAGE_1_AUTHORIZED_NOT_EXECUTED`\n\nPhase A / canonical_stage0_base_sha: `{A}` — read-back PASS.\nPhase B / authorization_commit_sha: `{B}` — read-back PASS.\nAuthorized seal SHA-256: `{SEAL}`\nContract SHA-256: `{CS}`\nManifest SHA-256: `{MS}`\nScientific diff: `NO SCIENTIFIC CHANGE`\nDrive Stage-0 seal folder/file: `1SFvk3A5fSzB4adPFIMxudgMdbooXVi3q` / `1hWN1mdJdx78jnsOlD2ZXF8htkf9e8QGL` — raw read-back PASS.\n\nStage 1: `NOT EXECUTED`.\nT1-T8: `NOT EXECUTED`.\nB4-N1...B4-N7: `NOT ESTABLISHED`.\nB4-CT: `NOT ESTABLISHED`.\nE6-N2: `[OPEN]`.\n\nBlocked seals — NEVER AUTHORIZE:\n'''+ '\n'.join('- `'+x+'`' for x in BLOCK)+f'''\n\nAuthorization JSON binds exactly the seal, contract, Phase-A SHA and `STAGE_1_AUTHORIZED_NOT_EXECUTED`; it does not self-reference Phase B.\n\nExact next action:\n{st['next_action']['instruction']}\n\nInvalid V1 T1-T8 drafts remain INVALID/NON-CANONICAL/DO NOT USE.\nNothing in this authorization proves the Collatz conjecture.\n'''; Path('START_HERE_CURRENT_HANDOFF.md').write_text(h,encoding='utf-8',newline='\n'); journal([{'event':'B4_V2_STAGE0_CANONICAL_ACCEPTANCE','timestamp_utc':now(),'task':P,'phase_a_commit_sha':A,'readback':'PASS','seal_sha256':SEAL,'scientific_diff':'NO SCIENTIFIC CHANGE','stage1_executed':False,'T1_T8_executed':False},{'event':'B4_V2_STAGE1_ONCE_ONLY_AUTHORIZATION','timestamp_utc':now(),'task':P,'phase_a_commit_sha':A,'authorization_commit_sha':B,'readback':'PASS','seal_sha256':SEAL,'contract_sha256':CS,'stage':SBST,'stage1_executed':False,'T1_T8_executed':False}]); imp=set(cfg['canonical_stage0_artifacts'])|set(extras)|{DEC,RA,AUTH,RB,TX,'START_HERE_CURRENT_HANDOFF.md','research_manager/RESEARCH_JOURNAL.jsonl'}
for p in sorted(imp):
 d=hf(p); up(st['integrity']['repository_files'],p,d); aa=an(p); aa and up(st['integrity']['archive_members'],aa,d)
wj('CURRENT_RESEARCH_STATE.json',st); q([sys.executable,'tools/build_current_archive.py']); build=json.loads(Path('CURRENT_ARCHIVE_BUILD.json').read_text()); assert build['zip_bytes']<100000000; q(['git','add','CURRENT_RESEARCH_STATE.json','START_HERE_CURRENT_HANDOFF.md','research_manager/RESEARCH_JOURNAL.jsonl',RB,TX,'CURRENT_ARCHIVE_BUILD.json','Collatz_Research_Archive_CURRENT.zip']); q(['git','commit','-m','Finalize B4 V2 authorization handoff']); F=o(['git','rev-parse','HEAD']); assert o(['git','rev-parse','HEAD^'])==B; vv=q([sys.executable,'tools/verify_handoff.py'],True); assert 'HANDOFF VERIFICATION: PASS' in vv.stdout; q(['git','push','origin','HEAD:main']); q(['git','fetch','origin','+refs/heads/main:refs/remotes/origin/main']); assert o(['git','rev-parse','refs/remotes/origin/main'])==F; fs=ja(F,'CURRENT_RESEARCH_STATE.json'); fa=ja(F,AUTH); fb=ja(F,'CURRENT_ARCHIVE_BUILD.json'); assert fs['active_task']['stage']==SBST and fs['active_integrator']['status']=='RELEASED' and fa==auth; verify(F,cfg); pd=Path('.canonical_persistence'); pd.mkdir(exist_ok=True); (pd/'HANDOFF_VERIFICATION.txt').write_text(vv.stdout); wj(pd/'PHASE_A_READBACK.json',RAO); wj(pd/'PHASE_B_READBACK.json',RBO); summary={**tx,'final_main_sha':F,'archive_sha256':fb['archive_sha256'],'archive_bytes':fb['zip_bytes'],'archive_members':fb['member_count'],'archive_headroom_bytes':100000000-fb['zip_bytes'],'handoff_verification':'PASS','github_final_readback':'PASS','lock_status':'RELEASED'}; wj(pd/'CANONICAL_TRANSACTION_FINAL_SUMMARY.json',summary); wj(pd/'GITHUB_FINAL_READBACK.json',{'final_main_sha':F,'active_task_stage':SBST,'authorization_binding':fa,'phase_a_commit_sha':A,'phase_b_commit_sha':B,'stage1_executed':False,'T1_T8_executed':False,'lock_status':'RELEASED','verdict':'PASS'})
for x in ['CURRENT_RESEARCH_STATE.json','START_HERE_CURRENT_HANDOFF.md','CURRENT_ARCHIVE_BUILD.json','research_manager/RESEARCH_JOURNAL.jsonl',AUTH,DEC,RA,RB,TX,'Collatz_Research_Archive_CURRENT.zip']: (pd/Path(x).name).write_bytes(Path(x).read_bytes())
print(json.dumps(summary,sort_keys=True))
